name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Run tests
        run: npm run test:ci
